### PR TITLE
cleanup npm, build cryptolib-js-*

### PR DESCRIPTION
**Pull request by opendata4ar**
remove all package-lock.json files as they yield to npm install failures (ENOENT: no such file or directory)

### CODE REVIEW

**Comment by garamond** [comment]
Sadly, the repo doesn't contain the frontend of the voting frontend (only for the module `online-voting-secure-data-manager`). The `cryptolib-js-*` modules are libraries used by the frontend.

**Comment by garamond** [comment]
If you have Node 7 installed on your system then the `engines` key in the `package.json` files is applied, and the build fails.

```
> scytl-bitwise@2.1.5-4 compile ~/src/evoting-solution/source-code/scytl-cryptolib/cryptolib-js-bitwise
> jshint lib spec

lib/index.js: line 94, col 27, 'byte' is defined but never used.

1 error
```

The build succeeds with Node 10.

**Comment by opendata4ar** [comment]
please merge

**Comment by garamond** [comment]
Thanks for your help!

**Pull request merged**
