### PR TITLE
patch for republik to build sources and view docs

### PR DESCRIPTION
**Pull request by opendata4ar**
apply this patch to https://gitlab.com/swisspost/evoting-solution at commit 33a046160a2a6718f7525faaa29630bdb22f52ab from 21.2.2019 (33a04616)

getting-started.patch is no longer applicable as head of https://gitlab.com/swisspost/evoting-solution has changed since getting-started.patch was created (error "patch does not apply")

### CODE REVIEW

**Comment by opendata4ar** [comment]
build successful. please review & merge

**Comment by garamond** [comment]
Nice! Can you update it to be applicable to the latest swisspost/evoting-solution HEAD?

**Comment by garamond** [comment]
Maybe we should specify the swisspost/evoting-solution SHA the patch applies to?

**Comment by opendata4ar** [comment]
SHA of commit at swisspost/evoting-solution is in the patch name (post-33a04616.patch) as well as in comments of 1st commit & this very pull request. swisspost/evoting-solution HEAD has advanced 4 commits since this pull request was submitted. To keep up and minimize work in progress, we may start working on another patch after this one has been merged.

**Pull request merged**
